In [2]:
import numpy as np

a = np.array([(1,2,3), (4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
import time
import sys

s = range(1000)
print(sys.getsizeof(5) * len(s))

d = np.arange(1000)
print(d.size *d.itemsize ) #less memory

28000
4000


In [ ]:
n = 100000000
l1 = range(n)
l2 = range(n)

a1 = np.arange(n)
a2 = np.arange(n)

start = time.time()
result = [(x,y) for x,y in zip (l1,l2)]
print((time.time() - start )* 1000)

start = time.time()
result = a1 + a2
print((time.time() - start )* 1000) #lesser time

15937.745332717896
11129.234552383423


In [13]:
np.array([(1,2,3) , (2,3,4)])
print(a.ndim)
print(a.itemsize)
print(a.dtype)
print(a.size)
print(a.shape)


2
4
int32
6
(2, 3)


In [28]:
a = np.array([(1,2,3) , (3,5,6)])
a = a.reshape(3,2)
print(a)

a = np.array([(1,2,3,4) , (5,6,7,8), (9,10,11,12)])
print(a)
print(a[0,2])
print(a[0: , 3]) #all the rows that includes 3rd index
print(a[0:2 , 3]) #all the rows TILL 2nd row that includes 3rd index
print(a[0:,2])

[[1 2]
 [3 3]
 [5 6]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3
[ 4  8 12]
[4 8]
[ 3  7 11]


In [34]:
a = np.linspace(1,3,5) # 10 values between 1 and 3
print(a)
print(a.min())
print(a.max())
print(a.sum())

[1.  1.5 2.  2.5 3. ]
1.0
3.0
10.0


In [36]:
#axis - 0 -> columns
#axis - 1 -> rows

#to calculate sum of all rows

a = np.array([(1,2,3,4) , (5,6,7,8), (9,10,11,12)])
print(a.sum(axis=1))

print(a.ravel())

[10 26 42]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
